generatorName: kotlin-spring
outputDir: samples/server/others/kotlin-springboot/allOf-discriminator
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_1/polymorphism-allof-and-discriminator.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  interfaceOnly: "true"
