package org.openapitools.model

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import org.openapitools.model.Bird
import org.openapitools.model.Robobird
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid

/**
 * 
 */
@JsonIgnoreProperties(
  value = ["another_discriminator"], // ignore manually set another_discriminator, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the another_discriminator to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "another_discriminator", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Bird::class, name = "ANOTHER_BIRD"),
      JsonSubTypes.Type(value = Robobird::class, name = "ANOTHER_ROBOBIRD")
)
sealed interface AnotherAnimal {
    val another_discriminator: kotlin.String
}

