package org.openapitools.model

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.annotation.JsonValue
import org.openapitools.model.Car
import org.openapitools.model.Truck
import org.openapitools.model.VehicleType
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid

/**
 * 
 */
@JsonIgnoreProperties(
  value = ["vehicleType"], // ignore manually set vehicleType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the vehicleType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "vehicleType", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Car::class, name = "CAR"),
      JsonSubTypes.Type(value = Truck::class, name = "TRUCK")
)
sealed interface Vehicle {
    val vehicleType: VehicleType
}

